open Warmup

let () = assert (tree_product (Leaf 13) = 13)
let () = assert (tree_product (Branch (Branch (Leaf 2, Leaf 4), Leaf 13)) = 104)
let () = assert (tree_min (Leaf 13) = 13)
let () = assert (tree_min (Branch (Branch (Leaf 2, Leaf 4), Leaf 13)) = 2)
let () = assert (tree_max (Leaf 13) = 13)
let () = assert (tree_max (Branch (Branch (Leaf 2, Leaf 4), Leaf 13)) = 13)
let () = assert (tree_range (Leaf 13) = (13, 13))
let () = assert (tree_range (Branch (Branch (Leaf 2, Leaf 4), Leaf 13)) = (2, 13))
let () = assert (tree_depth_range (Leaf 13) = (1, 1))
let () = assert (tree_depth_range (Branch (Branch (Leaf 2, Leaf 4), Leaf 13)) = (2, 3))
let () = assert (same_shape (Leaf 1)
                            (Leaf 1) = true)
let () = assert (same_shape (Leaf 1)
                            (Leaf 2) = true)
let () = assert (same_shape (Leaf 13)
                            (Branch (Leaf 2, Leaf 4)) = false)
let () = assert (same_shape (Branch (Leaf 1, Leaf 3))
                            (Branch (Leaf 2, Leaf 4)) = true)
let () = assert (same_shape (Branch (Branch (Branch (Leaf (Char.chr 48), Branch (Leaf (Char.chr 54), Leaf (Char.chr 56))), Branch (Leaf (Char.chr 51), Branch (Leaf (Char.chr 57), Leaf (Char.chr 55)))), Branch (Leaf (Char.chr 49), Branch (Branch (Leaf (Char.chr 52), Leaf (Char.chr 53)), Leaf (Char.chr 50)))))
                            (Branch (Branch (Branch (Leaf (Char.chr 48), Branch (Leaf (Char.chr 54), Leaf (Char.chr 56))), Branch (Leaf (Char.chr 51), Branch (Leaf (Char.chr 57), Leaf (Char.chr 55)))), Branch (Leaf (Char.chr 49), Branch (Branch (Leaf (Char.chr 52), Leaf (Char.chr 53)), Leaf (Char.chr 50))))) = true)
let () = assert (same_shape (Branch (Branch (Branch (Leaf (Char.chr 48), Branch (Leaf (Char.chr 54), Leaf (Char.chr 56))), Branch (Leaf (Char.chr 51), Branch (Leaf (Char.chr 57), Leaf (Char.chr 55)))), Branch (Leaf (Char.chr 49), Branch (Branch (Leaf (Char.chr 52), Leaf (Char.chr 53)), Leaf (Char.chr 50)))))
                            (Branch (Branch (Branch (Branch (Leaf (Char.chr 50), Leaf (Char.chr 54)), Branch (Leaf (Char.chr 54), Leaf (Char.chr 56))), Branch (Leaf (Char.chr 51), Branch (Leaf (Char.chr 57), Leaf (Char.chr 55)))), Branch (Leaf (Char.chr 49), Branch (Branch (Leaf (Char.chr 52), Leaf (Char.chr 53)), Leaf (Char.chr 50))))) = false)
